# Generated by Django 4.1.3 on 2023-04-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='options',
            field=models.ManyToManyField(blank=True, to='service.option'),
        ),
    ]
