# Generated by Django 4.1.3 on 2023-04-28 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_fqa'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('complete', 'Complete'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], default='pending', max_length=25),
        ),
    ]
