# Generated by Django 4.1.7 on 2023-04-29 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_orderd_product_ordered'),
        ('service', '0006_order_payment_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderdItem',
            new_name='OrderedItem',
        ),
        migrations.RenameModel(
            old_name='OrderdVariantOption',
            new_name='OrderedVariantOption',
        ),
    ]
