# Generated by Django 4.1.7 on 2023-05-04 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_ordereditem_sale_pricing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
