# Generated by Django 4.1.7 on 2023-05-04 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_remove_order_total_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fqa',
            new_name='Faq',
        ),
    ]
