# Generated by Django 4.1.3 on 2023-03-13 07:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_order_email_remove_order_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderaddress',
            name='email',
            field=models.EmailField(default='harun@e.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderaddress',
            name='first_name',
            field=models.CharField(default='harun', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderaddress',
            name='last_name',
            field=models.CharField(default='jeylan', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderaddress',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
