# Generated by Django 4.1.3 on 2023-03-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_orderaddress_email_orderaddress_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('none', 'NONE'), ('ppl', 'PPL'), ('ups', 'UPS'), ('dhl', 'SHL'), ('usps', 'Usps next day')], default='none', max_length=25),
        ),
    ]
