# Generated by Django 4.1.3 on 2023-03-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_order_delivery_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.FloatField(default=121),
            preserve_default=False,
        ),
    ]
