# Generated by Django 4.1.3 on 2023-03-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fulfillment_status',
            field=models.CharField(choices=[('complete', 'Complete'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('pending', 'Pending'), ('partially_fulfilled', 'Partially Fulfilled')], default='pending', max_length=25),
        ),
    ]
