# Generated by Django 4.1.3 on 2023-02-28 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_label_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='countries',
            field=models.ManyToManyField(blank=True, to='api.country'),
        ),
        migrations.AlterField(
            model_name='order',
            name='countries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.country'),
        ),
    ]
