# Generated by Django 4.1.3 on 2023-03-13 22:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_order_fulfillment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdproduct',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
