# Generated by Django 4.1.3 on 2023-03-13 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_orderdproduct_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdproduct',
            name='date',
        ),
    ]
