# Generated by Django 4.1.3 on 2023-03-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_review_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='email',
            field=models.EmailField(default='harunjeylan@gmail.com', max_length=100),
            preserve_default=False,
        ),
    ]
