# Generated by Django 4.1.3 on 2023-03-14 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_orderdproduct_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_adderss',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_adderss',
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_billing_address', to='api.orderaddress'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_shipping_address', to='api.orderaddress'),
        ),
    ]
