# Generated by Django 4.1.3 on 2023-03-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_review_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variantoption',
            name='option',
        ),
        migrations.AddField(
            model_name='variantoption',
            name='option',
            field=models.ManyToManyField(to='api.option'),
        ),
    ]
