# Generated by Django 4.1.3 on 2023-03-12 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_orderdvariantoption_orderdproduct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
    ]
