# Generated by Django 4.1.3 on 2023-03-12 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_order_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdvariantoption',
            old_name='options',
            new_name='option',
        ),
    ]
