# Generated by Django 4.1.3 on 2023-03-12 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('api', '0017_rename_options_orderdvariantoption_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_adderss',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_billing_adderss', to='account.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_adderss',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_shipping_adderss', to='account.address'),
        ),
    ]
