# Generated by Django 4.1.7 on 2023-04-26 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='product-images')),
                ('date', models.DateField(auto_now_add=True)),
                ('regular_pricing', models.FloatField()),
                ('sale_pricing', models.FloatField()),
                ('stock', models.FloatField()),
                ('fragile_product', models.BooleanField(blank=True, default=False)),
                ('max_allowed_temperature', models.CharField(blank=True, max_length=25, null=True)),
                ('biodegradable', models.BooleanField(blank=True, default=False)),
                ('frozen_product', models.BooleanField(blank=True, default=False)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('shipping_type', models.CharField(choices=[('fulfilled_by_seller', 'Fulfilled by Seller'), ('fulfilled_by_phoenix', 'Fulfilled by Phoenix')], default='fulfilled_by_seller', max_length=25)),
                ('global_delivery', models.CharField(choices=[('worldwide_delivery', 'Worldwide Delivery'), ('selected_countries', 'Selected Countries'), ('local_delivery', 'Local Delivery')], default='worldwide_delivery', max_length=25)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.brand')),
                ('countries', models.ManyToManyField(blank=True, to='service.country')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.discount')),
                ('images', models.ManyToManyField(blank=True, to='service.image')),
                ('orderd', models.ManyToManyField(blank=True, to='service.orderditem')),
                ('organize', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.organize')),
                ('reviews', models.ManyToManyField(blank=True, to='service.review')),
                ('variants', models.ManyToManyField(blank=True, to='service.variantoption')),
                ('wishes', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
