# Generated by Django 4.1.7 on 2023-04-27 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_variant_options'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='orderd',
        ),
        migrations.AddField(
            model_name='product',
            name='orderd',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.orderditem'),
        ),
    ]
