# Generated by Django 4.1.7 on 2023-04-29 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_orderd_product_orderd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='orderd',
            new_name='ordered',
        ),
    ]
