# Generated by Django 4.2.1 on 2023-05-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_orderd_product_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_information',
            field=models.TextField(blank=True, null=True),
        ),
    ]
