# Generated by Django 4.1.3 on 2022-11-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_product_long_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='harun@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
