# Generated by Django 4.1.3 on 2023-01-06 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_order_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='long_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='order',
            name='username',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_description',
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('worldwide_delivery', 'Worldwide Delivery'), ('selected_countries', 'Selected Countries'), ('local_delivery', 'Local Delivery')], default='local_delivery', max_length=25),
        ),
        migrations.AddField(
            model_name='order',
            name='fulfillment_status',
            field=models.CharField(choices=[('complete', 'Complete'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('complete', 'Complete'), ('pending', 'Pending'), ('partially_fulfilled', 'Partially Fulfilled')], default='pending', max_length=25),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='product-images'),
        ),
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('options', models.ManyToManyField(to='api.option')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regular_pricing', models.FloatField()),
                ('sale_pricing', models.FloatField()),
                ('stock', models.FloatField()),
                ('shipping_type', models.CharField(choices=[('fulfilled_by_seller', 'Fulfilled by Seller'), ('fulfilled_by_phoenix', 'Fulfilled by Phoenix')], default='fulfilled_by_seller', max_length=25)),
                ('global_delivery', models.CharField(choices=[('worldwide_delivery', 'Worldwide Delivery'), ('selected_countries', 'Selected Countries'), ('local_delivery', 'Local Delivery')], default='worldwide_delivery', max_length=25)),
                ('fragile_product', models.BooleanField(blank=True, default=False)),
                ('biodegradable', models.BooleanField(blank=True, default=False)),
                ('frozen_product', models.BooleanField(blank=True, default=False)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('countries', models.ManyToManyField(to='api.countries')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='countries',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.countries'),
        ),
        migrations.AddField(
            model_name='product',
            name='organize',
            field=models.ManyToManyField(related_name='organize', to='api.variants'),
        ),
        migrations.AddField(
            model_name='product',
            name='variants',
            field=models.ManyToManyField(related_name='variants', to='api.variants'),
        ),
    ]
