# Generated by Django 4.1.3 on 2023-04-29 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customernote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customernote',
            old_name='user',
            new_name='customer',
        ),
    ]
