# Generated by Django 4.1.3 on 2023-01-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_address_options_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('default', 'Default'), ('billing', 'Billing'), ('shipping', 'Shipping')], default='default', max_length=12),
        ),
    ]
